//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrawlerNet.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int maxConcurrentThreads {
            get {
                return ((int)(this["maxConcurrentThreads"]));
            }
            set { 
                this["maxConcurrentThreads"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int maxPagesToCrawl {
            get {
                return ((int)(this["maxPagesToCrawl"]));
            }
            set
            {
                this["maxPagesToCrawl"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int maxPagesToCrawlPerDomain {
            get {
                return ((int)(this["maxPagesToCrawlPerDomain"]));
            }
            set
            {
                this["maxPagesToCrawlPerDomain"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int maxPageSizeInBytes {
            get {
                return ((int)(this["maxPageSizeInBytes"]));
            }
            set
            {
                this["maxPageSizeInBytes"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mozilla/5.0 (Windows NT 6.3; Trident/7.0; rv:11.0) like CrawlerNet")]
        public string userAgentString {
            get {
                return ((string)(this["userAgentString"]));
            }
            set
            {
                this["userAgentString"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int crawlTimeoutSeconds {
            get {
                return ((int)(this["crawlTimeoutSeconds"]));
            }
            set
            {
                this["crawlTimeoutSeconds"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("text/html, text/plain")]
        public string downloadableContentTypes {
            get {
                return ((string)(this["downloadableContentTypes"]));
            }
            set
            {
                this["downloadableContentTypes"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isUriRecrawlingEnabled {
            get {
                return ((bool)(this["isUriRecrawlingEnabled"]));
            }
            set
            {
                this["isUriRecrawlingEnabled"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isExternalPageCrawlingEnabled {
            get {
                return ((bool)(this["isExternalPageCrawlingEnabled"]));
            }
            set
            {
                this["isExternalPageCrawlingEnabled"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isExternalPageLinksCrawlingEnabled {
            get {
                return ((bool)(this["isExternalPageLinksCrawlingEnabled"]));
            }
            set
            {
                this["isExternalPageLinksCrawlingEnabled"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int httpServicePointConnectionLimit {
            get {
                return ((int)(this["httpServicePointConnectionLimit"]));
            }
            set
            {
                this["httpServicePointConnectionLimit"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int httpRequestTimeoutInSeconds {
            get {
                return ((int)(this["httpRequestTimeoutInSeconds"]));
            }
            set
            {
                this["httpRequestTimeoutInSeconds"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int httpRequestMaxAutoRedirects {
            get {
                return ((int)(this["httpRequestMaxAutoRedirects"]));
            }
            set
            {
                this["httpRequestMaxAutoRedirects"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool isHttpRequestAutoRedirectsEnabled {
            get {
                return ((bool)(this["isHttpRequestAutoRedirectsEnabled"]));
            }
            set
            {
                this["isHttpRequestAutoRedirectsEnabled"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isHttpRequestAutomaticDecompressionEnabled {
            get {
                return ((bool)(this["isHttpRequestAutomaticDecompressionEnabled"]));
            }
            set
            {
                this["isHttpRequestAutomaticDecompressionEnabled"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isSendingCookiesEnabled {
            get {
                return ((bool)(this["isSendingCookiesEnabled"]));
            }
            set
            {
                this["isSendingCookiesEnabled"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int minAvailableMemoryRequiredInMb {
            get {
                return ((int)(this["minAvailableMemoryRequiredInMb"]));
            }
            set
            {
                this["minAvailableMemoryRequiredInMb"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int maxMemoryUsageInMb {
            get {
                return ((int)(this["maxMemoryUsageInMb"]));
            }
            set
            {
                this["maxMemoryUsageInMb"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int maxMemoryUsageCacheTimeInSeconds {
            get {
                return ((int)(this["maxMemoryUsageCacheTimeInSeconds"]));
            }
            set
            {
                this["maxMemoryUsageCacheTimeInSeconds"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int maxCrawlDepth {
            get {
                return ((int)(this["maxCrawlDepth"]));
            }
            set
            {
                this["maxCrawlDepth"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isForcedLinkParsingEnabled {
            get {
                return ((bool)(this["isForcedLinkParsingEnabled"]));
            }
            set
            {
                this["isForcedLinkParsingEnabled"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int maxRetryCount {
            get {
                return ((int)(this["maxRetryCount"]));
            }
            set
            {
                this["maxRetryCount"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int minRetryDelayInMilliseconds {
            get {
                return ((int)(this["minRetryDelayInMilliseconds"]));
            }
            set
            {
                this["minRetryDelayInMilliseconds"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isRespectRobotsDotTextEnabled {
            get {
                return ((bool)(this["isRespectRobotsDotTextEnabled"]));
            }
            set
            {
                this["isRespectRobotsDotTextEnabled"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isRespectMetaRobotsNoFollowEnabled {
            get {
                return ((bool)(this["isRespectMetaRobotsNoFollowEnabled"]));
            }
            set
            {
                this["isRespectMetaRobotsNoFollowEnabled"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isRespectAnchorRelNoFollowEnabled {
            get {
                return ((bool)(this["isRespectAnchorRelNoFollowEnabled"]));
            }
            set
            {
                this["isRespectAnchorRelNoFollowEnabled"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isIgnoreRobotsDotTextIfRootDisallowedEnabled {
            get {
                return ((bool)(this["isIgnoreRobotsDotTextIfRootDisallowedEnabled"]));
            }
            set
            {
                this["isIgnoreRobotsDotTextIfRootDisallowedEnabled"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CrawlerNet")]
        public string robotsDotTextUserAgentString {
            get {
                return ((string)(this["robotsDotTextUserAgentString"]));
            }
            set
            {
                this["robotsDotTextUserAgentString"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int maxRobotsDotTextCrawlDelayInSeconds {
            get {
                return ((int)(this["maxRobotsDotTextCrawlDelayInSeconds"]));
            }
            set
            {
                this["maxRobotsDotTextCrawlDelayInSeconds"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int minCrawlDelayPerDomainMilliSeconds {
            get {
                return ((int)(this["minCrawlDelayPerDomainMilliSeconds"]));
            }
            set
            {
                this["minCrawlDelayPerDomainMilliSeconds"] = value;
            }
        }
    }
}